version: "3"

services:
  app:
    container_name: example-app
    build: ./
    environment:
      API_KEY: ${API_KEY}
    ports:
      - 8000:8000
    volumes:
      - ./:/var/code
    command: tail -f /dev/null
